# This rule is not used by the project ofen itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ofen.cybozu.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ofen
    app.kubernetes.io/managed-by: kustomize
  name: imageprefetch-admin-role
rules:
- apiGroups:
  - ofen.cybozu.io
  resources:
  - imageprefetches
  verbs:
  - '*'
- apiGroups:
  - ofen.cybozu.io
  resources:
  - imageprefetches/status
  verbs:
  - get
