[book]
language = "en"
src = "."
title = "Ofen Documentation"

[output.html]
git-repository-url = "https://github.com/cybozu-go/ofen"
edit-url-template = "https://github.com/cybozu-go/ofen/edit/main/docs/{path}"
site-url = "/ofen/"
